name: mix test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.13.4, 1.14.0]
        otp: [25.1, 24.3.4]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
